### ISSUE TITLE
User uploads not working for web enabled pixel

### ISSUE THREAD

**Issue by alinke** [alinke/PIXEL#4]
Am testing on the Raspberry Pi. The newly updated GIF does show up correctly in the animations pane but when clicking it, this error message occurs:

INFO: animation handler is writing animations/5CnSka7.gif
Checking PIXEL activity in Pixel.
Pixel is stopping PIXEL activity in Pixel..
Decoding 5CnSka7.gif
ERROR  Could not find animations/gifsource/5CnSka7.gif in the JAR file
PIXEL LED panel resolution is: 32
Selected LED panel is different than the encoded GIF, need to re-encode...
ERROR  Could not find animations/gifsource/5CnSka7.gif in the JAR file
java.io.FileNotFoundException: /home/pi/pixel/animations/decoded/5CnSka7.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.onebeartoe.pixel.hardware.Pixel.getDecodedfps(Pixel.java:460)
	at org.onebeartoe.pixel.hardware.Pixel.writeAnimation(Pixel.java:1369)
	at org.onebeartoe.web.enabled.pixel.controllers.AnimationsHttpHandler.writeImageResource(AnimationsHttpHandler.java:42)
	at org.onebeartoe.web.enabled.pixel.controllers.ImageResourceHttpHandler.getHttpText(ImageResourceHttpHandler.java:77)
	at org.onebeartoe.network.TextHttpHandler.handle(TextHttpHandler.java:19)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)

**Comment by onebeartoe** [comment]
Al you mentioned elsewhere, "the code is looking for gifsource in the JAR itself".  My gut feeling is you are correct.  The code, as is, expects the source of the animation in the JAR.  I am pretty sure we can add logic to look on the filesystem if is not in the JAR.

**Comment by alinke** [comment]
latest release works now with .gifs and also the redirect upload screen works fine. I was able to stream and write a user uploaded gif just fine. However user uploaded still images not yet working.

**Comment by alinke** [comment]
Nit pick issue, after doing a user upload, the screen is re-directed back to the scrolling text pane. Would be better if after uploading, the user was taken back to the same screen he/she was already on (typically still image or animations)

**Comment by onebeartoe** [comment]
I'll look to see what is going on with uploaded stills.

On the redirect, I don't think that is nit picking.  The should user should go back to where they were before the upload.  Can we make this a separate issue (from this upload issue)?

**Comment by alinke** [comment]
cool, I created a new issue for the return tab

**Comment by onebeartoe** [comment]
Just saw it, thanks.

**Comment by onebeartoe** [comment]
I just committed a fix for still image uploads.  Please pull the latest changes to verify it works as expected.

**Comment by alinke** [comment]
Cool thx , will try out shortly

**Comment by alinke** [comment]
fixed
